apiVersion: v1
kind: Namespace
metadata:
  name: octank
  labels:
    app: octank
---
apiVersion: v1
kind: Secret
metadata:
  name: pgbconfig
  namespace: octank
type: Opaque
data:
  userlist.txt: %userlisttxt%
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbconfig
  namespace: octank
data:
  pgbouncer.ini: |
    %pgbouncerini%
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-deployment
  namespace: octank
  labels:
    app: pgbouncer
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      restartPolicy: Always
      containers:
      - name: pgbouncer
        image: ksarabu/pgbouncer:1.16.1
        ports:
         - containerPort: 6432
        volumeMounts:
         - name: pgbconfigmap
           subPath: pgbouncer.ini
           mountPath: /etc/pgbouncer/pgbouncer.ini
           readOnly: true
         - name: pgbconfig
           subPath: userlist.txt
           mountPath: /etc/pgbouncer/userlist.txt
           readOnly: true
      volumes:
        - name: pgbconfig
          secret:
            secretName: pgbconfig
        - name: pgbconfigmap
          configMap:
            name: pgbconfig
---
apiVersion: v1
kind: Service
metadata:
  name: octank-pgb
  namespace: octank
  labels:
    app: pgbouncer-service
spec:
  type: ClusterIP
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      protocol: TCP
      port: 6432
      targetPort: 6432
---
